version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    ports:
      - "4444:4444"
    volumes:
      - ./chrome-profile:/home/seluser/chrome-profile
    environment:
      - TZ=Asia/Kuala_Lumpur

  app:
    build: .
    volumes:
      - ./config:/app/config
      - ./credentials:/app/credentials
      - ./checkpoint:/app/checkpoint
    environment:
      - TZ=Asia/Kuala_Lumpur
      - SELENIUM_HOST=chrome
    depends_on:
      - chrome
